---
title: "leaflet_test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

https://dennishi0925.github.io/leaflet_test.html

```{r message=F,warning=F}
library(tidyverse)
library(sf)
library(leaflet)

# sf_intersection_grid %>% write_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_grid.rds")
sf_intersection_city <- read_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_city.rds")
# sf_intersection_town %>% write_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_town.rds")
# sf_intersection_stat_0st %>% write_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_stat_0st.rds")
# sf_intersection_stat_1st %>% write_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_stat_1st.rds")
sf_intersection_stat_2nd <- read_rds("/Users/dennistseng/Documents/TUIC/data/intersection/sf_intersection_stat_2nd.rds")


# color_town_pcnt <- colorNumeric(palette = "Blues", domain = sf_intersection_town$pcnt_stat_min)
# color_town_ccnt <- colorNumeric(palette = "Blues", domain = sf_intersection_town$ccnt_city_min)
# color_town_ncnt <- colorNumeric(palette = "Blues", domain = sf_intersection_town$ncnt_grid_min)

color_city_pcnt <- colorNumeric(palette = "Blues", domain = sf_intersection_city$pcnt_stat_min)
color_city_ccnt <- colorNumeric(palette = "BuGn", domain = sf_intersection_city$ccnt_city_min)
color_city_ncnt <- colorNumeric(palette = "BuPu", domain = sf_intersection_city$ncnt_grid_min)

# color_grid_pcnt <- colorNumeric(palette = "Blues", domain = sf_intersection_grid$pcnt_stat_min)
# color_grid_ccnt <- colorNumeric(palette = "BuGn", domain = sf_intersection_grid$ccnt_city_min)
# color_grid_ncnt <- colorNumeric(palette = "BuPu", domain = sf_intersection_grid$ncnt_grid_min)

color_stat2nd_pcnt <- colorNumeric(palette = "Blues", domain = sf_intersection_stat_2nd$pcnt_stat_min)
color_stat2nd_ccnt <- colorNumeric(palette = "BuGn", domain = sf_intersection_stat_2nd$ccnt_city_min)
color_stat2nd_ncnt <- colorNumeric(palette = "BuPu", domain = sf_intersection_stat_2nd$ncnt_grid_min)

map <- leaflet(sf_intersection_city) %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stamen.Toner) %>%
  addPolygons(
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_city_pcnt(pcnt_stat_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                       bringToFront = TRUE),
    group = "city_pcnt") %>%
  addPolygons(
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_city_ccnt(ccnt_city_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                       bringToFront = TRUE),
    group = "city_ccnt") %>%
  addPolygons(
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_city_ncnt(ncnt_grid_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                                     bringToFront = TRUE),
    group = "city_ncnt") %>%
  addPolygons(
    data = sf_intersection_stat_2nd,
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_stat2nd_pcnt(pcnt_stat_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                                        bringToFront = TRUE),
    group = "stat_pcnt") %>%
  addPolygons(
    data = sf_intersection_stat_2nd,
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_stat2nd_ccnt(ccnt_city_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                                     bringToFront = TRUE),
    group = "stat_ccnt") %>%
  addPolygons(
    data = sf_intersection_stat_2nd,
    stroke = T, color = "black", weight = 1,
    opacity = 0.7, smoothFactor = 0.1, fillOpacity = 0.7,
    fillColor = ~color_stat2nd_ncnt(ncnt_grid_min), highlightOptions = highlightOptions(color = "white", weight = 2,
                                                                                        bringToFront = TRUE),
    group = "stat_ncnt") %>%
  # Layers control
  addLayersControl(
    baseGroups = c("city_pcnt", "city_ccnt", "city_ncnt","stat_pcnt", "stat_ccnt", "stat_ncnt"),
    # overlayGroups = c("Quakes", "Outline"),
    options = layersControlOptions(collapsed = FALSE)
  )

map
```